---
abstract: 'A collocation of homework, classwork and exams'
author:
  - 'Dr Bean <drbean at (a) cpan dot (.) org>'
build_requires:
  FindBin: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 3.101461, CPAN::Meta::Converter version 2.101461'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Grades
requires:
  Carp: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 0
  Moose::Autobox: 0
  MooseX::Declare: 0
  MooseX::Getopt: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  POSIX: 0
  Scalar::Util: 0
  Try::Tiny: 0
  YAML: 0
resources:
  homepage: http://search.cpan.org/dist/Grades/
  repository: http://svn.openfoundry.org/ttb/beans
version: 0.10
