---
abstract: 'Grading of a league of players (ie class of students.)'
author:
  - 'Dr Bean <drbean, followed by the at mark (@), cpan, then a dot, and finally, org>'
build_requires:
  Pod::Coverage::Moose: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Grades
provides:
  Grades:
    file: lib/Grades.pm
    version: 0.08
  Grades::Script:
    file: lib/Grades.pm
  Grades::Types:
    file: lib/Grades/Types.pm
    version: 0.06
requires:
  Carp: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 0
  MooseX::Declare: 0
  MooseX::Getopt: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  POSIX: 0
  Scalar::Util: 0
  Try::Tiny: 0
  YAML: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Grades
  license: http://dev.perl.org/licenses/
  repository: http://svn.openfoundry.org/ttb/beans/
version: 0.08
